---
- hosts: localhost
  gather_facts: no
  roles:
          - role: aws-ec2


- hosts: k8s_master
  become_user: root
  become: yes
  gather_facts: no
  roles:
          - role: config_k8s_master


- hosts: k8s_slave
  vars_prompt:
          - name: token
            prompt: Enter the token to join the kubernetes cluster 
            private: no
  become_user: root
  become: yes
  gather_facts: no
  roles:
          - role: config_k8s_slave